/velocity_control_node:
  ros__parameters:
    odometry_topic: odometry/filtered
    bicycle_control_topic: bicycle_control
    motor_topic: cmd_motor
    
    update_rate: 50.0
    linear_vel_PID_params: [3.0, 0.0, 0.0]
    angular_vel_PID_params: [0.25, 0.0, 0.0]
    wheel_base_length: 0.1
